name: Slack Notification

on: [push, pull_request, issues, issue_comment, pull_request_review_comment]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send Slack message
        uses: ./
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
